### PR TITLE
Try for a syntax theme in light mode as well

### PR DESCRIPTION
**Pull request by asinghvi17**
WIP, not sure if this will work.  If it does, I'll steal it for MakieGallery.

### CODE REVIEW

**Comment by Datseris** [comment]
Sorry, not really familiar with this stuff. What is this supposed to do?

**Comment by asinghvi17** [comment]
I'm trying to get a good syntax highlighting theme in Documenter for light mode, since the normal one is a bit bland.

**Comment by Datseris** [comment]
so does it work? can you paste a screenshot of how the new theme looks?

**Comment by asinghvi17** [comment]
Hmm, doesn't quite work - I get an error `ERROR: LoadError: File to import not found or unreadable: highlightjs/foundation.`.  @mortenpi, could you recommend the best way to go about this?

**Comment by mortenpi** [comment]
You need to actually add the highlight.js theme source file to the repository too (e.g. [as we have for a11y in Documenter](https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/html/scss/highlightjs/a11y-dark.css)). The path is relative to the SCSS file.

**Comment by asinghvi17** [comment]
I'm testing this out at https://github.com/JuliaPlots/MakieGallery.jl/pull/249

**Comment by Datseris** [comment]
screenshot of result plis

**Pull request closed without merging**
